// 멀티모듈 프로젝트에서 bootJar { enabled = true } + jar { enabled = false } 설정을 위해 해당 플러그인이 필요
plugins {
    id 'org.springframework.boot'
}

// 멀티모듈 프로젝트에서 core / domain 모듈은 그 자체로 독립적으로 실행 가능한 JAR 로 생성되지 않도록 방지
bootJar { enabled = false } // 내장 Tomcat 포함하는 (바로 실행 가능한) JAR 생성 가능 여부
jar { enabled = true }      // 순수 라이브러리성 (바로 실행 불가능한) JAR 생성 가능 여부 <- core / domain 은 다른 API 에 포함되는 서브 JAR

dependencies {
}